apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-macos
    access: proxy
    orgId: 1
    url: http://influxdb:8181
    database: mybucket
    jsonData:
      version: SQL
      insecureGrpc: true
      timeInterval: "10s"
      metadata:
        - database: mybucket
    secureJsonData:
      token: unused
    isDefault: true
    editable: false
